[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "scikit-build==0.15.0",
    "cmake>=3.18",
    "nanobind>=0.0.5",
    "ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"
